<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>练习使用axios.js</title>

    <script src="../script/vue.js"></script>
    <script src="../script/axios.js"></script>

</head>
<body>
    <div id="app">
        <input type="button" value="点击" title="实验的button">
        
    </div>

    <script>
        //程序环境搭建：
        var test = new Vue({
            el: "#app",
            data: {
                message: "显示内容"
            }
        })

        // 2.1 使用axios框架
        // 2.2 学习使用JSON解析
        //Promise教程地址： https://www.bilibili.com/video/av75041024?from=search&seid=8714593936565971216  (https://www.bilibili.com/video/av75041024)
        //Axios教程地址：   https://www.bilibili.com/video/av71987780?from=search&seid=10958499840519641616 (https://www.bilibili.com/video/av75039519)

        //Json API （使用JSON-Server 建立）：localhost:8989

        /*
            异步的层级关系：
            XMLHttpRequest
            ||
            Promise
            ||
            axios
        */

        //============================================
        //XMLHttpRequest 接口的属性与方法

        function Fn(a, b, c) {
            this.a = a;
            this.b = b;
            this.c = c;
            return this;
        }
        var a = 1, b = 2, c = 3;
        const fn = new Fn(a, b, c);
        console.log(Fn.prototype);




        //============================================
        //使用Promise
        //区别 函数对象 与 实例对象

        //两种回调函数： 同步调用，异步调用

        //1. 同步回调函数
        const arr = [1,2,3,4,5,6];
        arr.forEach(item => {
            console.log(item);
        });

        //2. 异步回调函数
        setTimeout(() => {
            console.log("timeout callback()");
        }, 0);


        //JS里的Error处理
        //常见的内置错误：
        //ReferenceError 变量不存在
        //TypeError 数据类型不正确
        //RangeError 数值不在允许的范围内
        //SyntaxError 语法错误
        //============================================
        //错误的处理
        //捕获错误： try ... catch ...
        //抛出错误： throw error
        try {
            let d;
            console.log(d.xxx);
        } catch(err) {
            console.log(err);
        }

        //或者

        try {
            throw new Error('错误发生');
        }catch(err) {
            console.log(err.message);
        }

        //===========使用Promise===========
        //概念： Promise是JS中解决异步编程的新的解决方案
        //Promise是一个构造函数
        //promise对象封装一个异步操作并可以获取其结果
        /*
        promise状态的改变：
                    ~~>(fulfill) 执行了 resolve()  --成功结果数据：value
        pending ~~
                    ~~>(reject) 执行了 reject()  --失败的结果数据：reason
        ****只有这两种变化
        */
        //promise 的基本使用
        //1. 创建一个 Promise 对象

        const p = new Promise((resolve, reject) => {
            // 2. 执行异步操作

            setTimeout(() => {
                const time = Date.now();
                if (time % 2 == 0) {
                    // 3.1. 如果成功了，调用 resolve(value)
                    resolve('成功的数据，time = ' + time);
                } else {
                    // 3.2. 如果失败了，调用 reject(reason)
                    reject('失败的数据，time = ' + time);
                }
            }, 1000)


        });

        p.then(
            value => {
                console.log('成功的回调', value);
            },
            reason => {
                console.log('失败的回调', reason);
            }
        );

        //和传统方式比，即异步操作必须在开始操作之前指定回调函数，
        //Promise可以在任务启动后甚至是有了结果之后再指定回调函数

        //此外，Promise 可以解决回调地狱的问题
        //e.g.
        doSomething()
        .then(function(result){
            return doSomethingElse(result);
        })
        .then(function (NewResult) {
            return doTirdThing(newResult);
        })
        .then(function (finalResult) {
            console.log('最终的结果' + finalResult);
        })
        .catch(failureCallback);

        //或者使用async / await
        //e.g.
        async function request() {
            try {
                const result = await doSomething();
                const newResult = await doSomthingElse(result);
                const finalResult = await doTirdThing(newResult);
                console.log(finalResult);
            } catch (error) {
                failureCallback(error);
            }
        }

        //Promise 的API说明
        //Promise的函数对象方法：
        /*
            Promise.all(iterable)
            Promise.race(iterable)
            Promise.reject(reason)
            Promise.resolve(value)
        */
        //Promise的对象方法
        /*
            Promise.prototype.then(onFulfilled, onRejected)
            Promise.prototype.catch(onRejected)
            Promise.prototype.finally(onFinally)
        */



        //============================================
        //使用Axios



    </script>
</body>
</html>